### ISSUE TITLE
investigate why TotalHitsM4a1 is 0

### ISSUE THREAD

**Issue by moritzpflueger** [megaclan3000/megaclan3000#116]
investigate why TotalHitsM4a1 is 0 for every player 

steps:
1.) checkout correct Branch (implement weapons chart, or master if PR is accepted already)
2.) observe that hits for M4a1 is 0 for every player

**Comment by pinpox** [comment]
Will look into it. Can I merge the other branch for the weapons table safely before fixing this?

**Comment by moritzpflueger** [comment]
let me do 1 final commit

**Comment by pinpox** [comment]
I'll just wait for the ready status
