### ISSUE TITLE
[details/overview] investigate how to merge K/D and ADR Chart

### ISSUE THREAD

**Issue by moritzpflueger** [megaclan3000/megaclan3000#118]
### description

K/D Ratio (Kill/Death) and ADR (Average Damage per Round) are often used tightly together and it might be possible to merge both charts into one.

ADR: a value below 100 is considered Bad, above 100 is considered great (100 is player health at beginning of each round)

### Todo
Find way to appropiatlely show K/D + ADR Info 

(Merging both charts might not be the perfect answer)

**Comment by pinpox** [comment]
Closing for now. The charts will show data based on parsed from demos in future and will require a different implemetation due to #131
