### ISSUE TITLE
[details/weapons]: Show use in weapons chart

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#123]
The weapons chart shows the accuracy, it should show the kills instead. e.g. while the data is correct in the table, here `awp` is shown first in the chart (highest accuracy). In this example the ak47 should be first, since it has the most kills registered.

If we make the table sortable (#117 ), we could investigate if the chart could update dynamically aswell, but `TotalKills` should be the default sorting here.

![image](https://user-images.githubusercontent.com/1719781/85944207-4c232b80-b935-11ea-8ece-2b11636e7337.png)

**Comment by moritzpflueger** [comment]
That's easily done

are you sure though? Compare with csgo-stats
![image](https://user-images.githubusercontent.com/65345718/85945757-2a7b7180-b940-11ea-8a12-8cde3525667f.png)

we should ad a tab navigation to change the xAxis Data (Accuracy, Kills, Shots) as the user likes and have kills as the default selected

**Comment by pinpox** [comment]
> we should ad a tab navigation to change the xAxis Data (Accuracy, Kills, Shots) as the user likes and have kills as the default selected

Could we link this to the sortable table headers? So if the user sorts the table by `Kills` the graphic updates too.
Not sure how well that would work, but it might get rid of any extra buttons needed.

**Comment by pinpox** [comment]
> That's easily done
> 
> are you sure though? Compare with csgo-stats

I just realized csgo-stats *is* doing what I suggested I think. The percentage shown above each bar shows the accuracy, but the _heigth_ of the bar is showing the kills.
