### ISSUE TITLE
Show detailed online status

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#19]
- In Game
- ...

**Comment by moritzpflueger** [comment]
@pinpox please elaborate

**Comment by pinpox** [comment]
@moritzpflueger Currently the state of the player is reported as either "online" or "offline". There is more information available that could be shown here, like the steam client does. Possible values are e.g.:

- Playing CS:GO
- Playing other game
- Offline
- Online

But, let's put this issue on hold. It is just a possible enhancement, not strictly necessary and not part of the `Deploy History` Milestone. Let's get the issues from that Milestone fixed first, then move on to further enhancements.
