### ISSUE TITLE
[details/overview]: Make graphs full width and center

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#81]
![image](https://user-images.githubusercontent.com/1719781/85124698-a122bb80-b22a-11ea-9de4-a431ffb812a5.png)

- Resize to full width
- Center
- Add headers

**Comment by moritzpflueger** [comment]
assign me please

**Comment by pinpox** [comment]
@moritzpflueger  you are assigned.  Start from the `rework-details` branch, since I have already made changes and create your own branch from there:

```
git checkout rework-details
git checkout -b full-width-graph
```

Start by looking at `/templates/details.html`. The templates are rendered by the server and are basic html/js + `{{ golang specific markers}}` used to include other templates.
