### ISSUE TITLE
[details/last match]: Implement template for "Last match section"

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#83]
- Implement template
- Remove placeholder picture
- Add data
- Add template as to /details.html template

**Comment by pinpox** [comment]
I'll setup the basic template without much styling, but containing all necessary data variables to make the frontend development easy.

As soon as it works, I'll transfer the issue to @moritzpflueger to take care of the design aspects.

**Comment by pinpox** [comment]
- New blank template created
- Included in main template (`details.html`)
- Created draft pull request for new branch
- Updated Issue and PR

**Comment by moritzpflueger** [comment]
### Weapons Ids?
from LastMatch Object I recieve the ID of the matches favorite Weapon.

In order to display the weapon's name and icon, I would need to know which Weapon has which ID. 

Can you provide? @pinpox

**Comment by pinpox** [comment]
@moritzpflueger Have not yet found out the mapping, it seems not to be documented in the steam API docs.
I **think** the numbers shown here are the correct id's https://tf2b.com/itemlist.php?gid=730
