### ISSUE TITLE
[details/weapons]: Implement weapon charts and table

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#85]
![image](https://user-images.githubusercontent.com/1719781/85125363-c663f980-b22b-11ea-92bd-3d29f91c3b6f.png)

- Replace pie-chart with new library
- Fill in missing table values
- Prettify table with colors and icons
- Remove placeholder graphic

**Comment by moritzpflueger** [comment]
@pinpox can you please elaborate on 
>Replace pie-chart with new library

what's the new library?

**Comment by moritzpflueger** [comment]
nevermind ;)
>The charts library used throughout the project is echarts. Both charts in the screenshot above are still using a different library and have to be replaced by new ones in /templates/chart-maps.html. Maybe the two charts can be merged into one or displayed in a different form.

>The echarts exmaples page shows most possiblities, the implementation should be very similar to /templates/chart-accuracy.html

>So basically, pick a good visualisation from the echarts exmples and look at /templates/chart-accuracy.html to implement /templates/chart-maps.html mostly from scratch
