### ISSUE TITLE
[Details/Overview] solve chart width problem with collapsible class

### ISSUE THREAD

**Issue by moritzpflueger** [megaclan3000/megaclan3000#94]
### description

somehow the `.collapsible-body` class interferes with the correct registration of the initial chart width. Resizing the browser will trigger the chart to recieve the correct width. 

### todo

1. re-integrate `.collapsible-body` (was temporarily disabled in #93)
2. find way to have chart have full width intially.

### issue
if having the chart-container width on 100% the chart width gets registured with 100px instead of the parent container width

**Comment by pinpox** [comment]
collapsibles are not strictly required, just some form of structure for the different sections. Maybe try tabs or other options from the materialize library

**Comment by moritzpflueger** [comment]
used tabs instead of collapsibles and it works just fine 👍
